export const INTERFACE_TYPE = {
  AuthMiddleware: Symbol.for("AuthMiddleware"),
  UserController: Symbol.for("UserController"),
  UserInteractor: Symbol.for("UserInteractor"),
  AuthRepositoryImpl: Symbol.for("AuthRepositoryImpl"),
  AuthServiceImpl: Symbol.for("AuthServiceImpl"),
  AuthInteractorImpl: Symbol.for("AuthInteractorImpl"),
  AuthController: Symbol.for("AuthController"),
  Mailer: Symbol.for("Mailer"),
  UserRepositoryImpl: Symbol.for("UserRepositoryImpl"),
  MailerImpl: Symbol.for("MailerImpl"),
  Logger: Symbol.for("Logger"),
  StorageBucketImpl: Symbol.for("StorageBucketImpl"),
  ErrorHandler: Symbol.for("ErrorHandler"),
  ErrorMiddleWare: Symbol.for("ErrorMiddleWare"),
  RoleRepositoryImpl: Symbol.for("RoleRepositoryImpl"),
  RoleInteractorImpl: Symbol.for("RoleInteractorImpl"),
  RoleController: Symbol.for("RoleController"),
  PermissionRepositoryImpl: Symbol.for("PermissionRepositoryImpl"),
  PermissionInteractorImpl: Symbol.for("PermissionInteractorImpl"),
  PermissionController: Symbol.for("PermissionController"),
  ComplaintTypeRepository: Symbol.for("ComplaintTypeRepository"),
  ComplaintTypeInteractor: Symbol.for("ComplaintTypeInteractor"),
  ComplaintTypeController: Symbol.for("ComplaintTypeController"),
  BaseLookupRepository: Symbol.for("BaseLookupRepository"),
  BaseLookupInteractor: Symbol.for("BaseLookupInteractor"),
  BaseLookupController: Symbol.for("BaseLookupController"),
  SoftwareRepositoryImpl: Symbol.for("SoftwareRepositoryImpl"),
  SoftwareInteractorImpl: Symbol.for("SoftwareInteractorImpl"),
  SoftwareController: Symbol.for("SoftwareController"),
  ComplaintCategoryRepositoryImpl: Symbol.for(
    "ComplaintCategoryRepositoryImpl"
  ),
  ComplaintCategoryInteractorImpl: Symbol.for(
    "ComplaintCategoryInteractorImpl"
  ),
  ComplaintCategoryController: Symbol.for("ComplaintCategoryController"),
  CallStatusRepositoryImpl: Symbol.for("CallStatusRepositoryImpl"),
  CallStatusInteractorImpl: Symbol.for("CallStatusInteractorImpl"),
  CallStatusController: Symbol.for("CallStatusController"),
  SetupStatusRepositoryImpl: Symbol.for("SetupStatusRepositoryImpl"),
  SetupStatusInteractorImpl: Symbol.for("SetupStatusInteractorImpl"),
  SetupStatusController: Symbol.for("SetupStatusController"),
  SubscriptionTypeRepositoryImpl: Symbol.for("SubscriptionTypeRepositoryImpl"),
  SubscriptionTypeInteractorImpl: Symbol.for("SubscriptionTypeInteractorImpl"),
  SubscriptionTypeController: Symbol.for("SubscriptionTypeController"),
  LeadStatusRepositoryImpl: Symbol.for("LeadStatusRepositoryImpl"),
  LeadStatusInteractorImpl: Symbol.for("LeadStatusInteractorImpl"),
  LeadStatusController: Symbol.for("LeadStatusController"),
  LeadNextStepRepositoryImpl: Symbol.for("LeadNextStepRepositoryImpl"),
  LeadNextStepInteractorImpl: Symbol.for("LeadNextStepInteractorImpl"),
  LeadNextStepController: Symbol.for("LeadNextStepController"),
  LeadRepositoryImpl: Symbol.for("LeadRepositoryImpl"),
  LeadInteractorImpl: Symbol.for("LeadInteractorImpl"),
  LeadController: Symbol.for("LeadController"),
  CustomerRepositoryImpl: Symbol.for("CustomerRepositoryImpl"),
  CustomerInteractorImpl: Symbol.for("CustomerInteractorImpl"),
  CustomerController: Symbol.for("CustomerController"),
  CustomerComplaintRepositoryImpl: Symbol.for(
    "CustomerComplaintRepositoryImpl"
  ),
  CustomerComplaintInteractorImpl: Symbol.for(
    "CustomerComplaintInteractorImpl"
  ),
  CustomerComplaintController: Symbol.for("CustomerComplaintController"),
  CustomerOutreachRepositoryImpl: Symbol.for("CustomerOutreachRepositoryImpl"),
  CustomerOutreachInteractorImpl: Symbol.for("CustomerOutreachInteractorImpl"),
  CustomerOutreachController: Symbol.for("CustomerOutreachController"),
  OutreachTypeRepositoryImpl: Symbol.for("OutreachTypeRepositoryImpl"),
  OutreachTypeInteractorImpl: Symbol.for("OutreachTypeInteractorImpl"),
  OutreachTypeController: Symbol.for("OutreachTypeController"),
  RescheduleRepositoryImpl: Symbol.for("RescheduleRepositoryImpl"),
  RescheduleInteractorImpl: Symbol.for("RescheduleInteractorImpl"),
  RescheduleController: Symbol.for("RescheduleController"),
};
