export const INTERFACE_TYPE = {
  AuthMiddleware: Symbol.for("AuthMiddleware"),
  UserController: Symbol.for("UserController"),
  UserInteractor: Symbol.for("UserInteractor"),
  AuthRepositoryImpl: Symbol.for("AuthRepositoryImpl"),
  AuthServiceImpl: Symbol.for("AuthServiceImpl"),
  AuthInteractorImpl: Symbol.for("AuthInteractorImpl"),
  AuthController: Symbol.for("AuthController"),
  Mailer: Symbol.for("Mailer"),
  UserRepositoryImpl: Symbol.for("UserRepositoryImpl"),
  MailerImpl: Symbol.for("MailerImpl"),
  Logger: Symbol.for("Logger"),
  StorageBucketImpl: Symbol.for("StorageBucketImpl"),
  ErrorHandler: Symbol.for("ErrorHandler"),
  ErrorMiddleWare: Symbol.for("ErrorMiddleWare"),
  RoleRepositoryImpl: Symbol.for("RoleRepositoryImpl"),
  RoleInteractorImpl: Symbol.for("RoleInteractorImpl"),
  RoleController: Symbol.for("RoleController"),
  PermissionRepositoryImpl: Symbol.for("PermissionRepositoryImpl"),
  PermissionInteractorImpl: Symbol.for("PermissionInteractorImpl"),
  PermissionController: Symbol.for("PermissionController"),
};
