export const INTERFACE_TYPE = {
  AuthMiddleware: Symbol.for("AuthMiddleware"),
  UserController: Symbol.for("UserController"),
  UserInteractor: Symbol.for("UserInteractor"),
  AuthRepositoryImpl: Symbol.for("AuthRepositoryImpl"),
  AuthServiceImpl: Symbol.for("AuthServiceImpl"),
  AuthInteractorImpl: Symbol.for("AuthInteractorImpl"),
  AuthController: Symbol.for("AuthController"),
  Mailer: Symbol.for("Mailer"),
  UserRepositoryImpl: Symbol.for("UserRepositoryImpl"),
  MailerImpl: Symbol.for("MailerImpl"),
  Logger: Symbol.for("Logger"),
  StorageBucketImpl: Symbol.for("StorageBucketImpl"),
  ErrorHandler: Symbol.for("ErrorHandler"),
  ErrorMiddleWare: Symbol.for("ErrorMiddleWare"),
  RoleRepositoryImpl: Symbol.for("RoleRepositoryImpl"),
  RoleInteractorImpl: Symbol.for("RoleInteractorImpl"),
  RoleController: Symbol.for("RoleController"),
  PermissionRepositoryImpl: Symbol.for("PermissionRepositoryImpl"),
  PermissionInteractorImpl: Symbol.for("PermissionInteractorImpl"),
  PermissionController: Symbol.for("PermissionController"),
  ComplaintTypeRepository: Symbol.for("ComplaintTypeRepository"),
  ComplaintTypeInteractor: Symbol.for("ComplaintTypeInteractor"),
  ComplaintTypeController: Symbol.for("ComplaintTypeController"),
  BaseLookupRepository: Symbol.for("BaseLookupRepository"),
  BaseLookupInteractor: Symbol.for("BaseLookupInteractor"),
  BaseLookupController: Symbol.for("BaseLookupController"),
  SoftwareRepositoryImpl: Symbol.for("SoftwareRepositoryImpl"),
  SoftwareInteractorImpl: Symbol.for("SoftwareInteractorImpl"),
  SoftwareController: Symbol.for("SoftwareController"),
  ComplaintCategoryRepositoryImpl: Symbol.for(
    "ComplaintCategoryRepositoryImpl"
  ),
  ComplaintCategoryInteractorImpl: Symbol.for(
    "ComplaintCategoryInteractorImpl"
  ),
  ComplaintCategoryController: Symbol.for("ComplaintCategoryController"),
  CallStatusRepositoryImpl: Symbol.for("CallStatusRepositoryImpl"),
  CallStatusInteractorImpl: Symbol.for("CallStatusInteractorImpl"),
  CallStatusController: Symbol.for("CallStatusController"),
  SetupStatusRepositoryImpl: Symbol.for("SetupStatusRepositoryImpl"),
  SetupStatusInteractorImpl: Symbol.for("SetupStatusInteractorImpl"),
  SetupStatusController: Symbol.for("SetupStatusController"),
  SubscriptionTypeRepositoryImpl: Symbol.for("SubscriptionTypeRepositoryImpl"),
  SubscriptionTypeInteractorImpl: Symbol.for("SubscriptionTypeInteractorImpl"),
  SubscriptionTypeController: Symbol.for("SubscriptionTypeController"),
};
