const Permissions = Object.freeze({
  CREATE_ROLE: "create:role",
  VIEW_ROLE: "view:role",
  UPDATE_ROLE: "update:role",
  DELETE_ROLE: "delete:role",
  VIEW_ROLES: "view:roles",
  CREATE_PERMISSION: "create:permission",
  VIEW_PERMISSION: "view:permission",
  VIEW_PERMISSIONS: "view:permissions",
  UPDATE_PERMISSION: "update:permission",
  DELETE_PERMISSION: "delete:permission",
  CREATE_USER: "create:user",
  VIEW_USER: "view:user",
  UPDATE_USER: "update:user",
  DELETE_USER: "delete:user",
  VIEW_USERS: "view:users",
  VIEW_SETTINGS: "view:settings",
  UPDATE_SETTINGS: "update:settings",
  VIEW_COMPLAINT_TYPES: "view:complaint_types",
  VIEW_COMPLAINT_TYPE: "view:complaint_type",
  CREATE_COMPLAINT_TYPE: "create:complaint_type",
  UPDATE_COMPLAINT_TYPE: "update:complaint_type",
  DELETE_COMPLAINT_TYPE: "delete:complaint_type",
  VIEW_SOFTWARES: "view:softwares",
  VIEW_SOFTWARE: "view:software",
  CREATE_SOFTWARE: "create:software",
  UPDATE_SOFTWARE: "update:software",
  DELETE_SOFTWARE: "delete:software",
  VIEW_COMPLAINT_CATEGORIES: "view:complaint_categories",
  VIEW_COMPLAINT_CATEGORY: "view:complaint_category",
  CREATE_COMPLAINT_CATEGORY: "create:complaint_category",
  UPDATE_COMPLAINT_CATEGORY: "update:complaint_category",
  DELETE_COMPLAINT_CATEGORY: "delete:complaint_category",
  VIEW_ALL_CALL_STATUSS: "view:call_statuss",
  VIEW_CALL_STATUS: "view:call_status",
  CREATE_CALL_STATUS: "create:call_status",
  UPDATE_CALL_STATUS: "update:call_status",
  DELETE_CALL_STATUS: "delete:call_status",
  CREATE_SETUP_STAUTS: "create:setup_status",
  VIEW_ALL_SETUP_STAUTS: "view:setup_statuss",
  VIEW_SETUP_STAUTS: "view:setup_status",
  UPDATE_SETUP_STAUTS: "update:setup_status",
  DELETE_SETUP_STAUTS: "delete:setup_status",
  CREATE_SUBSCRIPTION_TYPE: "create:subscription_type",
  VIEW_SUBSCRIPTION_TYPES: "view:subscription_types",
  VIEW_SUBSCRIPTION_TYPE: "view:subscription_type",
  UPDATE_SUBSCRIPTION_TYPE: "update:subscription_type",
  DELETE_SUBSCRIPTION_TYPE: "delete:subscription_type",
  CREATE_LEAD_STATUS: "create:lead_status",
  VIEW_ALL_LEAD_STATUS: "view:lead_statuss",
  VIEW_LEAD_STATUS: "view:lead_status",
  UPDATE_LEAD_STATUS: "update:lead_status",
  DELETE_LEAD_STATUS: "delete:lead_status",
  CREATE_LEAD: "create:lead",
  VIEW_LEADS: "view:leads",
  VIEW_LEAD: "view:lead",
  UPDATE_LEAD: "update:lead",
  DELETE_LEAD: "delete:lead",
  CREATE_CUSTOMER: "create:customer",
  VIEW_CUSTOMERS: "view:customers",
  VIEW_CUSTOMER: "view:customer",
  UPDATE_CUSTOMER: "update:customer",
  DELETE_CUSTOMER: "delete:customer",
  CREATE_CUSTOMER_COMPLAINT: "create:customer_complaint",
  VIEW_CUSTOMER_COMPLAINTS: "view:customer_complaints",
  VIEW_CUSTOMER_COMPLAINT: "view:customer_complaint",
  UPDATE_CUSTOMER_COMPLAINT: "update:customer_complaint",
  DELETE_CUSTOMER_COMPLAINT: "delete:customer_complaint",
  CREATE_CUSTOMER_OUTREACH: "create:customer_outreach",
  VIEW_CUSTOMER_OUTREACHS: "view:customer_outreachs",
  VIEW_CUSTOMER_OUTREACH: "view:customer_outreach",
  UPDATE_CUSTOMER_OUTREACH: "update:customer_outreach",
  DELETE_CUSTOMER_OUTREACH: "delete:customer_outreach",
  CREATE_OUTREACH_TYPE: "create:outreach_type",
  VIEW_OUTREACH_TYPES: "view:outreach_types",
  VIEW_OUTREACH_TYPE: "view:outreach_type",
  UPDATE_OUTREACH_TYPE: "update:outreach_type",
  DELETE_OUTREACH_TYPE: "delete:outreach_type",
  CREATE_RESCHEDULE: "create:reschedule",
  VIEW_RESCHEDULES: "view:reschedules",
  VIEW_RESCHEDULE: "view:reschedule",
  UPDATE_RESCHEDULE: "update:reschedule",
  DELETE_RESCHEDULE: "delete:reschedule",
} as const);

export default Permissions;
const UserPermissions = Object.values(Permissions);

export type PermissionType = typeof Permissions;

export { Permissions, UserPermissions };
