const Permissions = Object.freeze({
  CREATE_ROLE: "create:role",
  VIEW_ROLE: "view:role",
  UPDATE_ROLE: "update:role",
  DELETE_ROLE: "delete:role",
  VIEW_ROLES: "view:roles",
  CREATE_PERMISSION: "create:permission",
  VIEW_PERMISSION: "view:permission",
  VIEW_PERMISSIONS: "view:permissions",
  UPDATE_PERMISSION: "update:permission",
  DELETE_PERMISSION: "delete:permission",
  CREATE_USER: "create:user",
  VIEW_USER: "view:user",
  UPDATE_USER: "update:user",
  DELETE_USER: "delete:user",
  VIEW_USERS: "view:users",
  VIEW_SETTINGS: "view:settings",
  UPDATE_SETTINGS: "update:settings",
  VIEW_COMPLAINT_TYPES: "view:complaint_types",
  VIEW_COMPLAINT_TYPE: "view:complaint_type",
  CREATE_COMPLAINT_TYPE: "create:complaint_type",
  UPDATE_COMPLAINT_TYPE: "update:complaint_type",
  DELETE_COMPLAINT_TYPE: "delete:complaint_type",
  VIEW_SOFTWARES: "view:softwares",
  VIEW_SOFTWARE: "view:software",
  CREATE_SOFTWARE: "create:software",
  UPDATE_SOFTWARE: "update:software",
  DELETE_SOFTWARE: "delete:software",
  VIEW_COMPLAINT_CATEGORIES: "view:complaint_categories",
  VIEW_COMPLAINT_CATEGORY: "view:complaint_category",
  CREATE_COMPLAINT_CATEGORY: "create:complaint_category",
  UPDATE_COMPLAINT_CATEGORY: "update:complaint_category",
  DELETE_COMPLAINT_CATEGORY: "delete:complaint_category",
  VIEW_ALL_CALL_STATUSS: "view:call_statuss",
  VIEW_CALL_STATUS: "view:call_status",
  CREATE_CALL_STATUS: "create:call_status",
  UPDATE_CALL_STATUS: "update:call_status",
  DELETE_CALL_STATUS: "delete:call_status",
  CREATE_SETUP_STAUTS: "create:setup_status",
  VIEW_ALL_SETUP_STAUTS: "view:setup_statuss",
  VIEW_SETUP_STAUTS: "view:setup_status",
  UPDATE_SETUP_STAUTS: "update:setup_status",
  DELETE_SETUP_STAUTS: "delete:setup_status",
  CREATE_SUBSCRIPTION_TYPE: "create:subscription_type",
  VIEW_SUBSCRIPTION_TYPES: "view:subscription_types",
  VIEW_SUBSCRIPTION_TYPE: "view:subscription_type",
  UPDATE_SUBSCRIPTION_TYPE: "update:subscription_type",
  DELETE_SUBSCRIPTION_TYPE: "delete:subscription_type",
  CREATE_LEAD_STATUS: "create:lead_status",
  VIEW_ALL_LEAD_STATUS: "view:lead_statuss",
  VIEW_LEAD_STATUS: "view:lead_status",
  UPDATE_LEAD_STATUS: "update:lead_status",
  DELETE_LEAD_STATUS: "delete:lead_status",
} as const);

export default Permissions;
const UserPermissions = Object.values(Permissions);

export type PermissionType = typeof Permissions;

export { Permissions, UserPermissions };
