// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import config from "../../config/config.js";

dotenv.config({ path: new URL("../../../.env", import.meta.url).pathname });

const postgresUrl =
  process.env["POSTGRES_URL"]?.trim() ||
  config.postgres.url?.trim() ||
  `postgresql://${config.postgres.user}:${encodeURIComponent(config.postgres.password)}@${config.postgres.host}:${config.postgres.port}/${config.postgres.database}`;

export default defineConfig({
  schema: "src/framework/postgresql/prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: postgresUrl,
  },
});
