export * from "./base/IBaseRepository.js";
export * from "./base/IBaseLookupRepository.js";
export * from "./user/IUserRepository.js";
export * from "./auth/IAuthRepository.js";
export * from "./complaint_type/IComplaintTypeRepository.js";
export * from "./dashboard/IDashboardRepo.js";
export * from "./permission/IPermissionRepository.js";
export * from "./role/IRoleRepository.js";
export * from "./ticket/ITicketRepo.js";
